name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    uses: gerlynm/githubActions/.github/workflows/copy_to_s3.yml@main
    with:
      aws_key: ${{ AWS_KEY }}
      aws_secret_key: ${{ AWS_SRT }}
      s3_bucket_name: ${{ AWS_BCT }}
      aws_region: ${{ AWS_RGN }}
