name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    uses: gerlynm/githubActions/.github/workflows/copy_to_s3.yml@main
    with:
      aws_key: AKIA4UA6UN7CX4GI6GN5
      aws_secret_key: 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
      s3_bucket_name: testwithactionsofgithub
      aws_region: us-east-1

      
