name: Dev
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: sonarqube scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: "-Dsonar.projectKey=jerrii_jerrii   -Dsonar.projectName=jerrii -Dsonar.qualitygate.wait=true \n"

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source code
      uses: actions/checkout@master
    - name: setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - name: install dependencies
      run: npm install
